name: Flutter Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Locate and Build
        run: |
          # Nemo inda pubspec.yaml yake
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -print -quit)
          PROJECT_ROOT=$(dirname "$PUBSPEC_PATH")
          
          echo "Project found in: $PROJECT_ROOT"
          cd "$PROJECT_ROOT"
          
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
          
          # Matsar da APK zuwa inda GitHub zai gani
          mkdir -p $GITHUB_WORKSPACE/output
          cp build/app/outputs/flutter-apk/app-release.apk $GITHUB_WORKSPACE/output/ramadan-tafsir.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ramadan-tafsir-app-release
          path: output/ramadan-tafsir.apk
